services:
  postgres:
    image: postgres:15
    container_name: postgres_planwise
    environment:
      POSTGRES_USER: planwise_user
      POSTGRES_PASSWORD: planwise_pass
      POSTGRES_DB: planwise_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planwise_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U planwise_user -d planwise_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_planwise
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@planwise.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - planwise_net
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:

networks:
  planwise_net:
