spring:
  application:
    name: planwise
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://postgres:5432/planwise_db
    username: planwise_user
    password: planwise_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
